/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/dragon.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    // console.log(actions);
    actions.fly.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.dragon_flyFlap} />
        <skinnedMesh
          geometry={nodes.Dragon.geometry}
          material={materials.Dragon_Mat}
          skeleton={nodes.Dragon.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/dragon.glb')
