/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/bubble.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[4.75, -0.04, -0.1]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material}>
          <group scale={0.82} />
        </mesh>
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 0, -9.12]} rotation={[Math.PI / 2, 0, 0]} scale={10.65} />
        <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} position={[-0.84, -0.4, -8.97]} rotation={[Math.PI / 2, 0, 0]} scale={[-6.34, -3.56, -3.56]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bubble.glb')
